import math
import pygame

RES = WIDTH, HEIGHT = 1280, 800
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

FPS = 0


PLAYER_POS = HALF_WIDTH, HALF_HEIGHT #mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 1
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60


MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40



FLOOR_COLOR = (30, 30, 30)